<a href="https://colab.research.google.com/github/anaghasanthoshh/LearningTensorFlow/blob/main/Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The questions:


* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
* Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product.
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6 along the first axis.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9.








In [2]:
import tensorflow as tf

In [3]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

scalar=tf.constant(7)
vector=tf.constant([4,3])
Matrix=tf.constant([[4,3],
                   [5,6],
                   [7,8]])

In [10]:
#Find the shape, rank and size of the tensors you created in 1.
print(f"Rank of scalar = {scalar.ndim},shape={scalar.shape}")
print(f"Rank of vector = {vector.ndim},shape={vector.shape}")
print(f"Rank of Matrix = {Matrix.ndim},shape={Matrix.shape}")

Rank of scalar = 0,shape=()
Rank of vector = 1,shape=(2,)
Rank of Matrix = 2,shape=(3, 2)


In [14]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300].
#Using uniform to have random values spread over a range
tensor_A=tf.random.uniform([5,300])
tensor_B=tf.random.uniform([5,300])
tensor_A
tensor_B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.17478585, 0.9332496 , 0.46306193, ..., 0.8116441 , 0.87734497,
        0.1711334 ],
       [0.40378523, 0.6305046 , 0.8559545 , ..., 0.89506984, 0.3857839 ,
        0.22804451],
       [0.2886138 , 0.22328019, 0.9610033 , ..., 0.4777887 , 0.9047363 ,
        0.9317597 ],
       [0.3381704 , 0.28164363, 0.8767688 , ..., 0.6080277 , 0.42107975,
        0.2621708 ],
       [0.17646086, 0.00213015, 0.46782422, ..., 0.6024822 , 0.2751906 ,
        0.40694213]], dtype=float32)>

In [17]:
#Multiply the two tensors you created in 3 using matrix multiplication.
#we will be transposing the tensors instead of reshaping it.
mul=tf.matmul(tensor_A,tf.transpose(tensor_B))
mul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.70664 , 72.00567 , 79.45417 , 75.58652 , 79.72506 ],
       [69.9249  , 70.53951 , 76.21989 , 72.51013 , 76.34949 ],
       [77.45331 , 72.507805, 82.63014 , 71.82527 , 80.74091 ],
       [73.816956, 69.20767 , 76.6301  , 73.23216 , 78.23445 ],
       [73.20155 , 70.2954  , 79.65384 , 75.013176, 75.737114]],
      dtype=float32)>

In [22]:
#Multiply the two tensors you created in 3 using dot product.
mul_dot=tf.tensordot(tensor_A,tf.transpose(tensor_B),axes=1)
mul_dot

#Matmul and tensordot gives the same result in this case.

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.70664 , 72.00567 , 79.45417 , 75.58652 , 79.72506 ],
       [69.9249  , 70.53951 , 76.21989 , 72.51013 , 76.34949 ],
       [77.45331 , 72.507805, 82.63014 , 71.82527 , 80.74091 ],
       [73.816956, 69.20767 , 76.6301  , 73.23216 , 78.23445 ],
       [73.20155 , 70.2954  , 79.65384 , 75.013176, 75.737114]],
      dtype=float32)>

In [24]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
C=tf.random.uniform(minval=0,maxval=1,shape=[224,224,3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.9191761 , 0.9054084 , 0.8565513 ],
        [0.01535344, 0.6777594 , 0.32585502],
        [0.4554304 , 0.8404137 , 0.5113342 ],
        ...,
        [0.84419215, 0.3258072 , 0.93090236],
        [0.31369913, 0.11265039, 0.33614206],
        [0.2621112 , 0.8671905 , 0.06968749]],

       [[0.4463445 , 0.02339947, 0.59923184],
        [0.06236947, 0.8601054 , 0.51048076],
        [0.18704963, 0.78964365, 0.03492355],
        ...,
        [0.55352104, 0.5201963 , 0.86077857],
        [0.0808574 , 0.04938829, 0.53407574],
        [0.90916455, 0.18840528, 0.85645807]],

       [[0.12657225, 0.71189725, 0.4556508 ],
        [0.5385419 , 0.11431706, 0.02082443],
        [0.20430124, 0.33357227, 0.04641509],
        ...,
        [0.7051619 , 0.9076414 , 0.37434745],
        [0.5770658 , 0.08877838, 0.11852431],
        [0.01685452, 0.63203657, 0.35214603]],

       ...,

       [[0.05743814, 0.7485794 , 0.928537  ],
        [0.76

In [30]:
#Find the min and max values of the tensor you created in 6 along the first axis.
min=tf.reduce_min(C,axis=0)
min

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.96218491e-04, 5.90395927e-03, 1.85000896e-03],
       [3.22008133e-03, 2.31027603e-03, 2.24471092e-04],
       [8.31842422e-04, 3.88622284e-05, 3.98516655e-03],
       [1.09946728e-02, 4.39763069e-03, 1.38044357e-04],
       [1.18660927e-03, 8.31723213e-04, 6.81388378e-03],
       [1.38568878e-03, 1.12104416e-03, 1.50277615e-02],
       [6.04879856e-03, 1.23059750e-03, 3.73589993e-03],
       [1.05357170e-03, 3.19123268e-04, 2.05075741e-03],
       [7.05599785e-04, 2.77996063e-04, 1.06871128e-03],
       [3.62765789e-03, 1.25908852e-03, 6.26611710e-03],
       [1.76596642e-03, 1.25455856e-03, 2.21109390e-03],
       [1.07247829e-02, 1.09612942e-03, 6.01208210e-03],
       [4.20355797e-03, 9.84549522e-04, 7.46726990e-04],
       [3.80754471e-04, 7.26711750e-03, 4.61602211e-03],
       [8.13007355e-05, 6.05463982e-04, 1.04149580e-02],
       [1.00706816e-02, 6.15072250e-03, 2.51293182e-03],
       [2.98607349e-03, 8.29696655e-05

For further understanding:For a given matrix,

[[3, 7, 1],
 [2, 8, 6],
 [5, 4, 9]]


Min values along axis 0: [2, 4, 1]
Max values along axis 0: [5, 8, 9]

In [32]:
D=tf.constant([
 [3, 7, 1],
 [2, 8, 6],
 [5, 4, 9]])
tf.reduce_min(D,axis=0)
tf.reduce_min(D,axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [39]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
F=tf.random.uniform(minval=2,maxval=200,shape=[1, 224, 224, 3])
print(F,F.shape)
F_squeezed=tf.squeeze(F)
print(F_squeezed,F_squeezed.shape)

#squeeze removes the dimensions of size 1 from the shape of a tensor.


tf.Tensor(
[[[[127.33582  139.40578   17.572912]
   [173.8885   171.93126  191.99258 ]
   [ 95.398735 139.37587  123.57183 ]
   ...
   [ 41.75265  156.96657  116.76641 ]
   [102.163864 166.12694  197.18922 ]
   [ 39.613663  53.539974 150.264   ]]

  [[132.59398  103.29472  141.4462  ]
   [ 24.701836  41.6868   110.26645 ]
   [102.442924 118.87543  163.42921 ]
   ...
   [169.92273   12.391178 123.48428 ]
   [ 76.10541  114.747185 123.18391 ]
   [ 73.034904  23.273708 132.3559  ]]

  [[134.1159   141.18674   19.861454]
   [140.4214    53.89209   74.2002  ]
   [147.35864   42.74761   35.458393]
   ...
   [ 95.969635  21.84943   46.830627]
   [ 18.933155  73.53938  155.66559 ]
   [188.12769  147.41174   68.71764 ]]

  ...

  [[ 98.15843   44.008175 132.69446 ]
   [199.58047  161.61191  198.88802 ]
   [ 71.20524   69.118835  85.85261 ]
   ...
   [ 11.896002 148.78609   78.39543 ]
   [121.732574  62.091667   6.039304]
   [169.31116   26.563509 134.6319  ]]

  [[ 41.19089  190.7702    21.8681

In [34]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
E=tf.constant([4,6,2,3,1,7,8,10,45,0])
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [36]:
#One-hot encode the tensor you created in 9.
E_onehot=tf.one_hot(E,depth=10)
E_onehot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Thats all for the fundamentals-exercises!