Fundamentals using TensorFlow:

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
#create tensor with tf.constant
scalar= tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#No of dimesions of tensor
scalar.ndim

0

In [4]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [7]:
#create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix
#by default,datatype is int32

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:

tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

#Matrix and tensors might be used interchangably
scalar: a single number

vector: a number with direction

matrix: a 2-dimensional array of numbers

tensor: an n-dimensional array of numbers

In [15]:
#Creating tensors with variables
#create the same tensor with tf.variable as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
#Trying to change the value of changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Tensor created by constant cant be changed and the one created using variable is changeable.

## Creating Random tensors

In [18]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [26]:
random_3=tf.random.uniform(shape=(3,2))
print(random_3)

random_4=tf.random.normal(shape=(3,2))
print(random_4)

tf.Tensor(
[[0.10808861 0.9887432 ]
 [0.23820508 0.2262243 ]
 [0.62082505 0.9220743 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.04428944 -1.2783958 ]
 [ 0.25884077 -1.0087502 ]
 [-1.9580318  -1.5210143 ]], shape=(3, 2), dtype=float32)


## Shuffling tensors:

But why shuffle? Mainly helps in shuffling the training data

In [30]:

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim
tf.random.shuffle(not_shuffled)

#In this case the rows got shuffled.Every time we run it,the order will change.Expected behaviour
#On adding tf.random.seed(11) we can recreate the randomness
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)
#the o/p remains same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [40]:
#Global seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)#local seed

#Without the glbal seed,it still give randomly shuffled o/p.But if global seed is set,able to recreate randomness.
#So if both were given, they would act in conjunction with each other to recreate randomness


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [42]:
#Creating tensors or ones and zeroes.Similiar to numpy
tf.ones([10,7],dtype=tf.int32)


<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [46]:
tf.zeros([10,7])
#or
tf.zeros(shape=(10,7))
#or
tf.zeros({10,7})


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Converting numpy arrays into tensors :

In [47]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [48]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [54]:
B=tf.Variable(numpy_A)
B
#we can use variable aswell

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

## Attributes of tensors

In [56]:
B.shape
#Rank in tensor is the number of dimensions->

A.ndim

#Why couldnt we fetch ndim for tensor created with tf.Variable?

1

Casting to a type:

In [58]:
C=tf.cast(A,dtype=np.float16)
C

<tf.Tensor: shape=(24,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float16)>

## Tensor Aggregation :

In [59]:
D=tf.constant([[-10,-7],[-5,4]])
D

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,  -7],
       [ -5,   4]], dtype=int32)>

In [60]:
tf.abs(D)
#Gives the absolute value

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  4]], dtype=int32)>

In [63]:
#Min
min=tf.reduce_min(D)
print(f"min value :{min}")
max=tf.reduce_max(D)
print(f"max value :{max}")
mean=tf.reduce_mean(D)
print(f"mean value :{mean}")
sum=tf.reduce_sum(D)
print(f"sum value :{sum}")

min value :-10
max value :4
mean value :-4
sum value :-18


In [67]:
##tf.reduce_variance(D) Not this way.Import tfp

In [68]:
import tensorflow_probability as tfp

In [69]:
tfp.stats.variance(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 30], dtype=int32)>

In [71]:
tf.math.reduce_std(tf.cast(D,dtype=tf.float32))#reduce_std needs real or complex numbers.Hence the casting

<tf.Tensor: shape=(), dtype=float32, numpy=5.2201533>