<a href="https://colab.research.google.com/github/anaghasanthoshh/LearningTensorFlow/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals using TensorFlow:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [3]:
#create tensor with tf.constant
scalar= tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#No of dimesions of tensor
scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
#create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix
#by default,datatype is int32

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:

tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

#Matrix and tensors might be used interchangably
scalar: a single number

vector: a number with direction

matrix: a 2-dimensional array of numbers

tensor: an n-dimensional array of numbers

In [12]:
#Creating tensors with variables
#create the same tensor with tf.variable as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#Trying to change the value of changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Tensor created by constant cant be changed and the one created using variable is changeable.

## Creating Random tensors

In [14]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
random_3=tf.random.uniform(shape=(3,2))
print(random_3)

random_4=tf.random.normal(shape=(3,2))
print(random_4)

tf.Tensor(
[[0.76963675 0.10272598]
 [0.532516   0.72804546]
 [0.25315368 0.6909406 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.6237291   2.0850284 ]
 [-0.39064437 -0.8357063 ]
 [-0.3324129   0.9211137 ]], shape=(3, 2), dtype=float32)


## Shuffling tensors:

But why shuffle? Mainly helps in shuffling the training data

In [16]:

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim
tf.random.shuffle(not_shuffled)

#In this case the rows got shuffled.Every time we run it,the order will change.Expected behaviour
#On adding tf.random.seed(11) we can recreate the randomness
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)
#the o/p remains same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
#Global seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)#local seed

#Without the glbal seed,it still give randomly shuffled o/p.But if global seed is set,able to recreate randomness.
#So if both were given, they would act in conjunction with each other to recreate randomness


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [18]:
#Creating tensors or ones and zeroes.Similiar to numpy
tf.ones([10,7],dtype=tf.int32)


<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [19]:
tf.zeros([10,7])
#or
tf.zeros(shape=(10,7))
#or
tf.zeros({10,7})


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Converting numpy arrays into tensors :

In [20]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [22]:
B=tf.Variable(numpy_A)
B
#we can use variable aswell

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

## Attributes of tensors

In [23]:
B.shape
#Rank in tensor is the number of dimensions->

A.ndim

#Why couldnt we fetch ndim for tensor created with tf.Variable?

1

Casting to a type:

In [24]:
C=tf.cast(A,dtype=np.float16)
C

<tf.Tensor: shape=(24,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float16)>

## Tensor Aggregation :

In [25]:
D=tf.constant([[-10,-7],[-5,4]])
D

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,  -7],
       [ -5,   4]], dtype=int32)>

In [26]:
tf.abs(D)
#Gives the absolute value

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  4]], dtype=int32)>

In [27]:
#Min
min=tf.reduce_min(D)
print(f"min value :{min}")
max=tf.reduce_max(D)
print(f"max value :{max}")
mean=tf.reduce_mean(D)
print(f"mean value :{mean}")
sum=tf.reduce_sum(D)
print(f"sum value :{sum}")

min value :-10
max value :4
mean value :-4
sum value :-18


In [28]:
##tf.reduce_variance(D) Not this way.Import tfp

In [29]:
import tensorflow_probability as tfp

In [30]:
tfp.stats.variance(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 30], dtype=int32)>

In [31]:
tf.math.reduce_std(tf.cast(D,dtype=tf.float32))#reduce_std needs real or complex numbers.Hence the casting

<tf.Tensor: shape=(), dtype=float32, numpy=5.2201533>

## One hot encoding:

In [37]:
list_A=[0,1,2,3]
tf.one_hot(list_A,depth=4)
#Your depth should match the number of items in the list

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [38]:
#Custom On and off values:

tf.one_hot(list_A,depth=4,on_value="yes",off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

## Ensuring our Tensor run faste on GPU

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()
#checking the type running on

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi
#to check the type of gpu

Mon Nov 25 11:45:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--